apiVersion: v1
kind: Service
metadata:
	name: example-service
	labels:
		app: example-app
spec:
	type: ClusterIP
	selector:
		app: example-app
	ports:
		- protocol: TCP
		  name: web
		  port: 80
		  targetPort: 5000

---
apiVersion: v1
kind: ServiceMonitor
metadata:
	labels:
	name: example-app
	namespace: default
spec:
	endpoints:
	- interval: 30s
	  port: web
	selector:
		matchLabels:
			app: example-app
